[package]
name = "exec_callee"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exec_params = { path = "../../exec_params", default_features = false, features = ["no-std"] }
